# Generated by Django 4.2.11 on 2026-01-30 20:36

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('passarinhar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spice',
            name='image',
            field=thumbnails.fields.ImageField(default=2, upload_to='spice_images'),
            preserve_default=False,
        ),
    ]
