# Generated by Django 5.0.4 on 2026-01-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passarinhar', '0002_place_spice_sighting'),
    ]

    operations = [
        migrations.AddField(
            model_name='spice',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='spice',
            name='spice_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
