# Generated by Django 4.2.11 on 2026-02-01 18:54

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('passarinhar', '0003_alter_spice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spice',
            name='image',
            field=thumbnails.fields.ImageField(null=True, upload_to='spice_images/'),
        ),
    ]
