# Generated by Django 5.0.4 on 2026-01-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passarinhar', '0003_spice_scientific_name_spice_spice_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spice',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='spice',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
