# Generated by Django 5.0.4 on 2026-01-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passarinhar', '0004_alter_spice_name_alter_spice_scientific_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='latestObsDt',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='locId',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='subnational2Code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
