# Generated by Django 4.2.11 on 2026-02-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passarinhar', '0005_tabspecies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TabSpecies',
            new_name='DataZoneSpecies',
        ),
    ]
