# Generated by Django 5.0.4 on 2026-01-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passarinhar', '0005_place_latestobsdt_place_locid_place_subnational2code'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='numSpeciesAllTime',
            field=models.IntegerField(default=0),
        ),
    ]
