# Generated by Django 5.0.4 on 2026-01-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passarinhar', '0006_place_numspeciesalltime'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='favourite_places',
            field=models.ManyToManyField(blank=True, related_name='myplaces', to='passarinhar.place'),
        ),
    ]
