# Generated by Django 4.2.11 on 2026-02-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passarinhar', '0006_rename_tabspecies_datazonespecies'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataZoneSpecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SIS_ID', models.CharField(blank=True, max_length=20)),
                ('Sequence', models.CharField(blank=True, max_length=20)),
                ('Family', models.CharField(blank=True, max_length=20)),
                ('Scientific_name', models.CharField(blank=True, max_length=20)),
                ('Common_name', models.CharField(blank=True, max_length=20)),
                ('RL_Category', models.CharField(blank=True, max_length=20)),
                ('PE', models.CharField(blank=True, max_length=20)),
                ('PEW', models.CharField(blank=True, max_length=20)),
                ('Seabird', models.CharField(blank=True, max_length=20)),
                ('Waterbird', models.CharField(blank=True, max_length=20)),
                ('Landbird', models.CharField(blank=True, max_length=20)),
                ('Migratory_status', models.CharField(blank=True, max_length=20)),
                ('Ecosystem_Terrestrial', models.CharField(blank=True, max_length=20)),
                ('Ecosystem_Freshwater', models.CharField(blank=True, max_length=20)),
                ('Ecosystem_Marine', models.CharField(blank=True, max_length=20)),
                ('RL_AOO', models.CharField(blank=True, max_length=20)),
                ('Criteria_met_at_highest_level', models.CharField(blank=True, max_length=20)),
                ('RL_EOO', models.CharField(blank=True, max_length=20)),
                ('Population_size', models.CharField(blank=True, max_length=20)),
                ('Population_size_derivation', models.CharField(blank=True, max_length=20)),
                ('Current_population_trend', models.CharField(blank=True, max_length=20)),
                ('Current_population_trend_derivation', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='DataZoneSpecies',
        ),
    ]
