# Generated by Django 4.2.11 on 2026-02-04 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passarinhar', '0007_datazonespecie_delete_datazonespecies'),
    ]

    operations = [
        migrations.AddField(
            model_name='spice',
            name='DTScientific_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scientific', to='passarinhar.datazonespecie'),
        ),
    ]
