# Generated by Django 4.2.11 on 2026-03-04 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passarinhar', '0008_spice_dtscientific_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datazonespecie',
            name='Common_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='datazonespecie',
            name='Family',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='datazonespecie',
            name='Scientific_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='spice',
            name='DTScientific_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spice', to='passarinhar.datazonespecie'),
        ),
    ]
