# Generated by Django 4.2.11 on 2026-03-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passarinhar', '0009_alter_datazonespecie_common_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_BR', models.CharField(blank=True, max_length=64)),
                ('en', models.CharField(blank=True, max_length=64)),
                ('spp_group_id', models.CharField(blank=True, max_length=64)),
                ('species_code_begin', models.CharField(blank=True, max_length=64)),
                ('species_code_end', models.CharField(blank=True, max_length=64)),
                ('taxon_order_begin', models.CharField(blank=True, max_length=64)),
                ('taxon_order_end', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
