# Generated by Django 4.2.11 on 2026-03-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passarinhar', '0010_tabfamily'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesTaxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxon_order', models.IntegerField(blank=True)),
                ('species_code', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
