# Generated by Django 4.2.11 on 2026-03-13 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passarinhar', '0011_speciestaxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='spice',
            name='taxon_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spice_taxon_order', to='passarinhar.speciestaxonomy'),
        ),
    ]
