# Generated by Django 4.2.11 on 2026-03-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passarinhar', '0012_spice_taxon_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spice',
            name='url_spice_img',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='tabfamily',
            name='taxon_order_begin',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='tabfamily',
            name='taxon_order_end',
            field=models.FloatField(blank=True),
        ),
    ]
